'use strict';
// Copying these messages records no task, starts no chat and grants no permission.
(() => {
  const Workflow=typeof module!=='undefined'?require('./workflow.js'):window.StubbsJobsWorkflow;
  function taskPrompt(workspace,request){
    const send=request.type==='send',state=Workflow.task(request);
    const entry=`Abre la carpeta de Stubbs Jobs: ${workspace}. Lee AGENTS.md, status y app-status y comprueba únicamente la tarea ${request.id}. `;
    const scope='Esta petición solo autoriza comprobar el resultado; no reenviar, contactar ni cambiar permisos.';
    if(state.superseded)return entry+`Este intento anterior quedó comprobado como no enviado y esa comprobación se utilizó en el intento ${state.supersededByRequestId}. Conserva ambas pruebas y consulta el resultado del intento posterior; no reencoles ni reintentes el original. ${scope}`;
    if(state.interruptionUnconfirmed)return entry+`Una versión anterior anotó interrupted únicamente por falta de actividad. Eso no confirma que el chat o proceso anterior se detuviera y no transfiere su propietario. Comprueba el último paso con el chat anterior si está disponible. Antes de continuar, confirmar expresamente la detención real con su propietario o con la persona y usar ui-request-interrupt con proof concreto, expectedUpdatedAt y expectedExecutionId exactos e identificador propio; la operación conserva el historial y no inicia ni transfiere trabajo. Si no consta esa confirmación, explica la intervención pendiente y no repongas la tarea en cola. ${send?'Un not_sent anterior no habilita un reintento: después de confirmar la interrupción, comprobar de nuevo el portal y registrar ui-delivery-check antes de cualquier continuación. ':''}${scope}`;
    if(request.status==='running')return entry+`Conserva el propietario actual: la falta de actividad reciente no demuestra que se haya detenido. Si el chat anterior está disponible, pídele que conserve el último paso y registre interrupted cuando confirme la interrupción real. Si la persona confirma expresamente que ya detuvo ese chat o proceso, el agente puede usar ui-request-interrupt con proof concreto, expectedUpdatedAt y expectedExecutionId exactos e identificador propio; esto no inicia ni transfiere el encargo. Si no consta esa confirmación, explica la intervención pendiente. ${send?'No uses ui-delivery-check mientras siga running. Después de una interrupción comprobada, consulta el resultado original en el portal antes de cualquier continuación. ':''}No tomes trabajo running de otro chat ni declares terminada una tarea sin su resultado comprobado. ${scope}`;
    if(send&&request.status==='cancelled'){
      if(!state.cancelledStarted)return entry+'La tarea está cancelada y no consta un inicio real válido. Consulta su historial sin activar trabajo ni permisos. '+scope;
      if(state.deliveryDelivered)return entry+'El envío original ya tiene confirmación. Conserva ese recibo y el permiso retirado, sin repetir el formulario ni reponer la tarea en cola. '+scope;
      if(state.deliveryRecheckRequired)return entry+`El portal dejó comprobado que el intento original no se envió, pero esa comprobación ya no habilita otro envío. Consulta de nuevo únicamente esa solicitud en el portal y registra ui-delivery-check con prueba actual, paquete y destino originales y updatedAt esperado. Conserva cancelled y el permiso retirado: esta comprobación no reencola el original ni autoriza otro envío. Cualquier solicitud nueva necesitará su propio paquete comprobado y permiso vigente. ${scope}`;
      if(state.deliveryAbsent)return entry+'El portal dejó comprobado que no se envió. Conserva la tarea cancelada y el permiso retirado; no la repongas en cola. '+scope;
      return entry+`El permiso está retirado, pero el envío ya había comenzado. ${state.checkedUnknown?'La comprobación anterior no permitió confirmar el resultado: revisa de nuevo solo si hay una prueba nueva; si no, conserva la cancelación y explica el límite. ':''}Consulta únicamente si aquella solicitud original se presentó y qué paquete se utilizó. Registra ui-delivery-check con prueba, paquete, destino y updatedAt esperado. Si ya se envió, conserva sentAt y la confirmación sin repetir el formulario ni reactivar el permiso. not_sent o unknown conservan cancelled y no permiten reponer la tarea en cola. ${scope}`;
    }
    if(send&&state.deliveryChecked)return `Abre la carpeta de Stubbs Jobs: ${workspace}. Lee AGENTS.md, status y app-status. Retoma únicamente la tarea ${request.id}: el portal dejó comprobado que no se envió. Revalida que ui-delivery-check, el paquete exacto y su autorización siguen vigentes antes de reponerla en cola y registrar el inicio real con un identificador propio. Si la comprobación caducó, comprueba de nuevo el portal. Conserva la confirmación real al terminar. No apruebes paquetes en mi nombre ni amplíes esta tarea a otras ofertas o contactos.`;
    return entry+(send?`${state.checkedUnknown?'La comprobación anterior no permitió confirmar el resultado: comprueba de nuevo solo si hay una prueba nueva. ':''}El envío quedó sin confirmar: consulta el portal y comprueba si ya se presentó esa solicitud y qué versión se utilizó. Registra ui-delivery-check con la prueba, el paquete, el destino y updatedAt esperado. Si ya se envió, conserva la confirmación sin repetir el formulario. Si no se puede determinar, deja el bloqueo explicado. ${scope}`:'Comprueba el último paso registrado y explica dónde continuar. No tomes trabajo running de otro chat ni declares terminada una tarea sin su resultado comprobado.');
  }
  function backupPrompt(workspace,name){
    return `Abre la carpeta de Stubbs Jobs: ${workspace}. Comprueba la copia data/backups/${name} con check-backup. Usa restore para recuperarla en una carpeta nueva, sin sustituir la instalación actual. Compara el perfil, los CV, las ofertas, las solicitudes y los cambios posteriores. Muéstrame qué se recuperó y qué diferencias quedan antes de utilizar esa copia. Conservar los archivos originales y retirar los permisos antiguos de envío es obligatorio. Esta petición no autoriza búsquedas, solicitudes ni contactos.`;
  }
  const api={taskPrompt,backupPrompt};
  if(typeof module!=='undefined')module.exports=api;else window.StubbsJobsRecovery=api;
})();
